default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: '\.ipynb$'
      - id: end-of-file-fixer
        exclude: '\.ipynb$'
      - id: check-toml
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: check-added-large-files
        args: ["--maxkb=2000"]

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.5.1
    hooks:
      - id: black-jupyter

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.23.2
    hooks:
      - id: markdownlint-cli2

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: uv run pylint
        language: system
        types: [python]
        files: '^src/.*\.py$'
        args: ["--score=no"]

      - id: mypy
        name: mypy
        entry: uv run mypy src
        language: system
        types: [python]
        files: '^src/.*\.py$'
        pass_filenames: false
